# Based on "Deep Learning with R", appendix B (how to configure RStudio
# Server on AWS)
# Note
- name: Install RStudio Server and Keras on Ubuntu
  hosts: all
  become: yes

  tasks:
    - name: Add apt key for r-base
      apt_key:
        id: E084DAB9
        keyserver: keyserver.ubuntu.com
        state: present

    - name: Add RStudio CRAN repo to the list of providers for apt
      apt_repository:
        repo: deb http://cran.rstudio.com/bin/linux/ubuntu bionic-cran35/
        state: present

    - name: Install R base package
      apt:
        name: r-base
        update_cache: yes
